apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: todo-app
  labels:
    app: todo-application
data:
  DATABASE_NAME: tododb
  DATABASE_HOST: mysql-service
  BACKEND_PORT: "5000"
  FRONTEND_PORT: "80"

